#!/usr/bin/env bash

# This script opens all of my dev programs and puts them on the correct monitor/workspace

dell_second_monitor="DP-2"
samsung_primary_monitor="DP-0"

i3-msg workspace number 1
spotify &
sleep 2
i3-msg move workspace to output $dell_second_monitor
sleep 1

i3-msg workspace number 6
google-chrome &
sleep 2
i3-msg move workspace to output $dell_second_monitor
sleep 1

i3-msg workspace number 7
/usr/bin/konsole &
sleep 2
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 8
code &
sleep 2
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 9
idea &
sleep 3
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 10
obsidian &
sleep 2
i3-msg move workspace to output $samsung_primary_monitor