#!/usr/bin/env bash

# This script opens all of my dev programs and puts them on the correct monitor/workspace
# The sleep commands are needed to ensure programs are opened correctly before changing
# workspaces, they can probably be lowered.

dell_second_monitor="DP-2"
samsung_primary_monitor="DP-0"

i3-msg workspace number 1
i3-msg 'rename workspace 1 to 1:music'
spotify &
sleep 2
i3-msg move workspace to output $dell_second_monitor
sleep 1

i3-msg workspace number 2
i3-msg 'rename workspace 2 to 2:browser'
google-chrome &
sleep 2
i3-msg move workspace to output $dell_second_monitor
sleep 1

i3-msg workspace number 3
i3-msg 'rename workspace 3 to 3:random'
/usr/bin/konsole &
sleep 1 
i3-msg move workspace to output $samsung_primary_monitor
sleep 1


i3-msg workspace number 6
i3-msg 'rename workspace 6 to 6:db'
dbeaver-ce &
sleep 5 # DBeaver takes a long time to start
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 7
i3-msg 'rename workspace 7 to 7:terminal'
/usr/bin/konsole &
sleep 2
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 8
i3-msg 'rename workspace 8 to 8:text editor'
code &
sleep 2
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 9
i3-msg 'rename workspace 9 to 9:ide'
idea &
sleep 3
i3-msg move workspace to output $samsung_primary_monitor
sleep 1

i3-msg workspace number 10
i3-msg 'rename workspace 10 to 10:notes'
obsidian &
sleep 2
i3-msg move workspace to output $samsung_primary_monitor
