#!/usr/bin/env bash

# This script opens all of my dev programs and puts them on the correct monitor/workspace
# The sleep commands are needed to ensure programs are opened correctly before changing
# workspaces, they can probably be lowered.

# 1 - Music apps
i3-msg workspace number 1
i3-msg 'rename workspace 1 to 1:music'
spotify &
sleep 2

# 2 - Main web browser
i3-msg workspace number 2
i3-msg 'rename workspace 2 to 2:browser'
google-chrome &
sleep 2

# 3 - Random stuff, depends on what specfic task I'm working on
i3-msg workspace number 3
i3-msg 'rename workspace 3 to 3:random'
/usr/bin/konsole &
sleep 1 

# 4 - Extension development
i3-msg workspace number 4
i3-msg 'rename workspace 4 to 4:extension'
/usr/bin/konsole &
sleep 1 

# 5 - Remote SSH connections
i3-msg workspace number 5
i3-msg 'rename workspace 5 to 5:remote'
/usr/bin/konsole &
sleep 1 

# 6 - Database client
i3-msg workspace number 6
i3-msg 'rename workspace 6 to 6:db'
dbeaver-ce &
sleep 15 # DBeaver takes a long time to start

# 7 - Main dev terminals
i3-msg workspace number 7
i3-msg 'rename workspace 7 to 7:terminal'
/usr/bin/konsole &
sleep 2

# 8 - Text editors
i3-msg workspace number 8
i3-msg 'rename workspace 8 to 8:text editor'
code &
sleep 2

# 9 - Java IDE
#i3-msg workspace number 9
#i3-msg 'rename workspace 9 to 9:ide'
#idea &
#sleep 3
#i3-msg move workspace to output $samsung_primary_monitor
#sleep 1

# 10 - Notes
i3-msg workspace number 10
i3-msg 'rename workspace 10 to 10:notes'
$HOME/Downloads/Obsidian.AppImage &
